# CodeRabbit configuration
reviews:
  # Enable auto-reviews for all branches
  auto_review:
    enabled: true
    # Set to empty array to review all branches, or specify branch patterns
    base_branches: []
    # Alternative: specify patterns for branches to review
    # base_branches: ["main", "develop", "feature/*", "hotfix/*"]
  
  # Enable review status messages
  review_status: true
  
  # Configure pull request reviews
  pull_requests:
    # Review all PRs regardless of target branch
    auto_review: true
    # Include all files in review
    path_filters: []

# Optional: Configure which files to include/exclude
path_instructions:
  - path: "**/*.{js,ts,jsx,tsx,py,java,go,rs,cpp,c,h}"
    instructions: "Review code quality, security, and best practices"
  - path: "**/*.md"
    instructions: "Review documentation for clarity and accuracy"

# Language-specific settings
language_settings:
  javascript:
    review_level: "detailed"
  typescript:
    review_level: "detailed"
  python:
    review_level: "detailed"
